/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StatisticsTest {

    private final Statistics stats = new Statistics();
    private final int[] nums = {5, 2, 8, 1, 3};

    // For-loop Tests
    @Test
    void testMaxForLoop() {
        assertEquals(8, stats.maximumUsingForLoop(nums));
    }

    @Test
    void testMinForLoop() {
        assertEquals(1, stats.minimumUsingForLoop(nums));
    }

    @Test
    void testSumForLoop() {
        assertEquals(19, stats.sumUsingForLoop(nums));
    }

    @Test
    void testAvgForLoop() {
        assertEquals(19 / 5, stats.averageUsingForLoop(nums));
    }


    // Stream Tests
    @Test
    void testMaxStream() {
        assertEquals(8, stats.maximumUsingStream(nums));
    }

    @Test
    void testMinStream() {
        assertEquals(1, stats.minimumUsingStream(nums));
    }

    @Test
    void testSumStream() {
        assertEquals(19, stats.sumUsingStream(nums));
    }

    @Test
    void testAvgStream() {
        assertEquals(19 / 5, stats.averageUsingStream(nums));
    }


    // Add-On Tests
    @Test
    void testFilterEvenNumbers() {
        assertArrayEquals(new int[]{2, 8}, stats.filterEvenNumbers(nums));
    }

    @Test
    void testFilterOddNumbers() {
        assertArrayEquals(new int[]{5, 1, 3}, stats.filterOddNumbers(nums));
    }

    @Test
    void testAddFive() {
        assertArrayEquals(new int[]{10, 7, 13, 6, 8}, stats.addFive(nums));
    }

    @Test
    void testSquareNumbers() {
        assertArrayEquals(new int[]{25, 4, 64, 1, 9}, stats.squareNumbers(nums));
    }
}
